import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const registerStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B0B0B',
  },
  maskingView: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: hp(10.3),
    backgroundColor: '#0B0B0B',
    zIndex: 2,
  },
  scrollView: {
    flex: 1,
    paddingBottom: hp(15),
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: hp(12),
  },
  header: {
    flexDirection: 'row',
    marginTop: hp(2.5),
    marginLeft: wp(5),
  },
  backIcon: {
    width: hp(3),
    height: hp(3),
    marginTop: hp(0.5),
  },
  cntntTxt: {
    fontFamily: 'Poppins-Medium',
    width: wp(75),
    fontSize: hp(2),
    fontWeight: '500',
    color: '#FFF',
    marginLeft: wp(1),
    lineHeight: hp(3),
  },
  compBar: {
    width: wp(69.4),
    marginTop: hp(1.5),
  },
  numTxt: {
    fontFamily: 'Roboto-Medium',
    fontSize: hp(1.5),
    color: '#FFF',
    marginTop: hp(0.5),
    marginLeft: wp(1),
  },
  profileHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  profileContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: hp(4.5),
  },
  profileUser: {
    width: hp(17.5),
    height: hp(17.5),
    borderWidth: 1,
    borderColor: '#E7EA33',
    shadowColor: '#4A4A4A',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    borderRadius: hp(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  editIcon: {
    width: hp(5.5),
    height: hp(5.5),
    backgroundColor: '#FAFF00',
    borderRadius: hp(3.75),
    borderColor: '#0B0B0B',
    borderWidth: 6,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hp(11.5),
    marginLeft: hp(-3.5),
  },
  editIconStyle: {
    width: hp(2),
    height: hp(2),
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  editModalContainer: {
    position: 'absolute',
    bottom: 0,
  },

  editModal: {
    width: wp(100),
    height: hp(20),
    borderTopLeftRadius: hp(4.2),
    borderTopRightRadius: hp(4.2),
    backgroundColor: '#0B0B0B',
    borderBottomColor: '#FAFF00',
    borderWidth: 0.5,
  },
  genderModal: {
    width: wp(100),
    height: hp(44),
    borderTopLeftRadius: hp(4.2),
    borderTopRightRadius: hp(4.2),
    backgroundColor: '#0B0B0B',
  },
  headerBarStyle: {
    width: wp(30),
    height: hp(0.5),
  },
  headerBar: {
    alignSelf: 'center',
    marginTop: hp(1.3),
  },
  editModalHeader: {
    flexDirection: 'row',
    marginTop: hp(1.5),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  genderModalHeader: {
    flexDirection: 'row',
    marginTop: hp(2),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ppTxt: {
    color: '#FFF',
    fontFamily: 'Poppins-SemiBold',
    fontSize: hp(2.1),
    marginLeft: wp(5),
    fontWeight: '600',
  },
  genderTxt: {
    color: '#FFF',
    fontFamily: 'Poppins-SemiBold',
    fontSize: hp(2.1),
    marginLeft: wp(6.6),
    fontWeight: '600',
  },
  dltIcon: {
    width: hp(3.1),
    height: hp(3.1),
    marginRight: wp(5),
  },
  crossIcon: {
    width: hp(1.3),
    height: hp(1.3),
    marginRight: wp(6.6),
  },
  optionContainer2: {
    marginLeft: wp(6.6),
    marginTop: hp(2.7),
    gap: hp(3.7),
  },
  optionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioButton: {
    height: hp(2.4),
    width: hp(2.4),
    borderRadius: hp(2.4) / 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: wp(3.4),
    backgroundColor: 'rgba(242, 242, 242, 0.50)',
  },
  selectedRadioButton: {
    borderColor: 'rgba(242, 242, 242, 0.50)',
    borderWidth: 0.7,
    backgroundColor: '#000',
  },
  radioInner: {
    height: hp(1.3),
    width: hp(1.3),
    borderRadius: hp(1.3) / 2,
    backgroundColor: '#FFD700',
    borderWidth: 0.1,
  },
  optionText: {
    color: '#FFF',
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
    fontSize: hp(1.9),
  },
  input: {
    width: wp(64),
    height: hp(5.5),
    borderColor: 'rgba(255, 255, 255, 0.50)',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 14,
    color: '#FFF',
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
    paddingTop: 10,
    opacity: 0.7,
  },

  iconContainer: {
    flexDirection: 'row',
    marginTop: hp(1.8),
    justifyContent: 'space-around',
  },
  cameraIcn: {
    width: hp(4.6),
    height: hp(4.6),
    borderColor: '#666',
    borderWidth: 1,
    borderRadius: wp(5),
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(1.5),
  },
  cameraStyle: {
    width: hp(3),
    height: hp(3),
  },
  galleryStyle: {
    width: hp(2.5),
    height: hp(2.3),
  },
  icnTxt: {
    color: '#FFF',
    fontSize: hp(1.5),
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
    marginLeft: wp(-1),
  },
  galleryTxt: {
    color: '#FFF',
    fontSize: hp(1.5),
    fontFamily: 'Poppins-Regular',
    fontWeight: '400',
  },
  inputContainer: {
    marginLeft: wp(5),
    marginTop: hp(4.5),
    gap: hp(3.5),
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    backgroundColor: '#141414',
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: '#FAFF00',
    width: wp(90),
  },
  datePicker: {
    backgroundColor: '#141414',
    borderWidth: 0.5,
    width: wp(90),
    textDefaultColor: '#E6E0E9',
    textHeaderColor: '#E6E0E9',
    mainColor:'#FAFF00',
    selectedTextColor: '#381E72',
    textSecondaryColor: '#E6E0E9',

  },
  datePickerStyle: {
    borderRadius: 8,
  },
  datePickerFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginRight:wp(7),
    gap :wp(5),
    marginBottom:hp(1.5),
    marginTop:hp(-3)
  },
  inputWrapper: {
    width: wp(90),
    flexDirection: 'row',
    height: hp(7),
    borderColor: '#F2F2F2',
    borderWidth: 0.35,
    borderRadius: wp(1.6),
    flexShrink: 0,
  },
  inputField: {
    width: wp(54),
    lineHeight: hp(2.5),
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    paddingLeft: wp(5),
    fontSize: hp(1.875),
    opacity: 0.3,
  },
  errorText: {
    color: '#FF0033',
    fontSize: hp(1.5),
    fontWeight: '400',
    fontFamily: 'Poppins-Regular',
    marginTop: hp(1),
  },
  errorBorder: {
    borderColor: '#FF0033',
    borderWidth: 0.5,
  },
  calendar: {
    tintColor: '#E7EA33',
    width: hp(2.4),
    height: hp(2.4),
    alignSelf: 'center',
    marginLeft: wp(27),
  },
  cnclTxt:{
   color:'#FAFF00',
   fontSize:hp(1.6),
   fontWeight:'500',
   fontFamily:'Roboto-Medium'
  },
  downIcon: {
    tintColor: '#E7EA33',
    width: hp(2.6),
    height: hp(2.6),
    marginLeft: wp(26),
    alignSelf: 'center',
  },
  nxtBtn: {
    position: 'absolute',
    bottom: 0,
    width: wp(90),
    height: hp(7),
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowRadius: 11.8,
    elevation: 5,
    shadowOpacity: 0.25,
    borderWidth: 0.2,
    borderRadius: 3,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    marginBottom: hp(2),
    marginLeft: wp(5),
    zIndex: 3,
  },
  doneBtn: {
    position: 'absolute',
    bottom: 0,
    width: wp(90),
    height: hp(7),
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowRadius: 11.8,
    elevation: 5,
    shadowOpacity: 0.25,
    borderWidth: 0.2,
    borderRadius: 3,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    marginLeft: wp(5),
    marginTop: hp(3),
  },
  btnTxt: {
    fontSize: hp(2),
    fontWeight: '500',
    fontFamily: 'Poppins-Medium',
    color: '#faff00',
  },
  otpButtonContainer: {
    borderRadius: wp(2.2),
    height: hp(6),
    width: wp(90),
    padding: hp(0.04),
  },
  verifyOtpBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.2,
    width: wp(90),
    height: hp(6),
  },
  otpButtonContainer2: {
    backgroundColor: '#141414',
    borderRadius: wp(2.2),
    height: hp(6),
    width: wp(89.8),
    marginTop: 0.4,
    marginLeft: 0.5,
  },
  professionHeader:{
    flexDirection:'row',
    marginLeft:wp(5),
    marginTop:hp(2),
    alignItems:'center'
  },
  backIcon2:{
    width: hp(2.2),
    height: hp(2.2),
  },
  search2:{
  width:hp(2.5),
  height:hp(2.5),
  tintColor:'#FAFF00',
  },
  searchBar:{
    width:wp(90),
    marginLeft:wp(5),
    flexDirection:'row',
    height:hp(6),
    backgroundColor:"#222",
    marginTop:hp(2),
    borderRadius:8,
    alignItems:'center',
    paddingLeft:wp(3)

  },
  searchTxt:{
   marginLeft:wp(3),
   opacity:0.5,
   fontFamily: 'Poppins-Regular',
   width:wp(40),
  textAlignVertical:'center'

  },
  professionHeaderTxt: {
    fontFamily: 'Poppins-Medium',
    fontSize: hp(2.3),
    fontWeight: '500',
    color: '#F2F2F2',
    marginLeft: wp(2),
    lineHeight: hp(3),
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    width: wp(90),
    marginLeft: wp(5),
    marginTop:hp(4)
    
  },
  line: {
    flex: 1,
    height: 2,
    backgroundColor: '#303030',
  },
  orText: {
    color: '#656565',
    marginHorizontal: wp(3),
    fontFamily: 'Poppins-Regular',
    fontSize: hp(2),
    fontWeight: '500',
  },
});
