import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B0B0B',
  },
  container2: {
    flex: 1,
    backgroundColor: '#0B0B0B',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp(3.75),
    marginLeft: wp(5),
  },
  backIcon: {
    width: hp(2),
    height: hp(2),
  },
  backIconStyle: {
    resizeMode: 'contain',
  },
  title: {
    fontSize: hp(2.25),
    fontWeight: '800',
    color: '#F2F2F2',
    marginLeft: hp(3),
    fontFamily: 'Poppins-ExtraBold',
    lineHeight: hp(2.75),
  },
  weHaveSentContainer: {
    marginTop: hp(4),
  },
  toConfirmYourContainer: {
    fontSize: hp(1.875),
    lineHeight: hp(2.75),
    color: '#F2F2F2',
    textAlign: 'center',
    fontFamily: 'Poppins-ExtraLight',
    fontWeight: '300',
  },
  contentContainer:{
    width: wp(87),
    marginLeft:wp(5),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: wp(5),
    marginTop:hp(4)
  },
  weHaveSent: {
    lineHeight: hp(3.25),
    fontWeight: '300',
    textAlign: 'center',
    fontFamily: 'Poppins-ExtraLight',
    fontSize: hp(2),
  },
  txtStyle1:{
    fontFamily: 'Poppins-ExtraLight',
    fontWeight: '300',
  },
  emailText:{
    fontFamily: 'Poppins-Bold',
    fontWeight: '700',
    color: '#F2F2F2',
  },
  text: {
    fontWeight: '700',
    textAlign: 'center',
    fontFamily: 'Poppins-Bold',
    lineHeight: hp(3.25),
    fontSize: hp(2),
  },

  otpView: {
    width: wp(90),
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: hp(4),
    marginLeft: wp(5),
    justifyContent: 'space-between',
  },
  inputView: {
    width: hp(5.3),
    height: hp(5.3),
    borderWidth: 1,
    borderRadius: 7,
    textAlign: 'center',
    fontSize: hp(2.25),
    fontWeight: '500',
    borderColor: '#787878',
    borderStyle: 'solid',
  },
  errorMessage: {
    color: '#FF3E3E',
    marginLeft: wp(5),
    fontSize: hp(1.8),
    fontWeight: '300',
    fontFamily: 'Poppins-Light',
    marginTop: hp(1.5),
  },
  resendView: {
    flexDirection: 'row',
    marginTop: hp(4),
    marginBottom: hp(1.5),
    marginLeft: wp(5),
    alignItems: 'center',
  },
  drcTxt: {
    fontSize: hp(1.63),
    fontFamily: 'Poppins-Light',
    fontWeight: '300',
    lineHeight: hp(2.63),
    color: '#F2F2F2',
  },
  cntStyle: {
    marginLeft: wp(2),
    backgroundColor: '#0B0B0B',
  },
  cntTxt: {
    color: '#FAFF00',
    fontSize: hp(1.63),
    fontFamily: 'Poppins-Light',
    fontWeight: '300',
    paddingTop: hp(1.5),
  },
  separatorStyle: {
    color: '#FAFF00',
  },
  smsTxt: {
    fontSize: hp(1.5),
    fontWeight: '500',
    textTransform: 'uppercase',
    fontFamily: 'Poppins-Medium',
    color: 'grey',
    textAlign: 'center',
    marginLeft: wp(2),
  },
  msgTxt: {
    fontSize: hp(1.5),
    fontWeight: '500',
    fontFamily: 'Poppins-Medium',
    color: 'rgba(250, 255, 0, 0.3)',
    textAlign: 'center',
    marginLeft: wp(2),
  },
  smsBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    width: wp(28),
    height: hp(5),
    borderWidth: 1,
    borderColor: 'rgba(250, 255, 0, 0.1)',
    backgroundColor: '#141414',
    marginLeft: wp(5),
    marginBottom: hp(4),
  },
  smsStyle: {
    width: hp(1.4),
    height: hp(1.4),
  },
  msgStyle: {
    width: hp(1.9),
    height: hp(1.5),
    tintColor:'rgba(250, 255, 0, 0.3)'
  },
  resendBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    width: wp(32),
    height: hp(5),
    borderWidth: 1,
    borderColor: 'rgba(250, 255, 0, 0.3)',
    backgroundColor: '#141414',
    marginLeft: wp(5),
    marginBottom: hp(4),
  },
  otpButtonContainer: {
    borderRadius: wp(2.2),
    height: hp(6),
    width: wp(90),
    padding: hp(0.04),
  },
  verifyOtpBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 0.2,
    width: wp(90),
    height: hp(6),
  },
  loginBtn: {
    marginLeft: wp(5),
    width: wp(90),
    height: hp(6.6),
    shadowColor: 'rgba(0, 0, 0, 0.25)',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowRadius: 11.8,
    elevation: 5,
    shadowOpacity: 0.25,
    borderWidth: 0.2,
    borderRadius: 3,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
  },
  btnTxt: {
    fontSize: hp(2),
    fontWeight: '500',
    fontFamily: 'Poppins-Medium',
    color: '#faff00',
  },
  container3: {
    alignItems: 'center',
    marginBottom: hp(8),
  },
  popup: {
    width: wp(57),
    height: hp(4.63),
    backgroundColor: '#141414',
    borderRadius: hp(1),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo2: {
    height: hp(1.25),
    width: hp(2.4),
  },
  logoStyle: {
    height: hp(3),
    width: hp(3),
    backgroundColor: '#0B0B0B',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 3.5,
  },
  logoTxt: {
    fontSize: hp(1.5),
    color: '#F2F2F2',
    fontFamily: 'Poppins-Regular',
    marginLeft: wp(3),
    lineHeight: hp(3),
  },
});
